# API Keys for LLM services
OPENAI_API_KEY=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
GEMINI_API_KEY=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

# Set to: OPENAI, GEMINI, OPENAI-CLASSES, GEMINI-CLASSES
AI_LLM=OPENAI

# Logging configuration: OFF, ERROR, WARN, INFO, DEBUG, TRACE
LOG_LEVEL=OFF

MAX_TOKENS=800

TEMPERATURE=0.5